name: Build Release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          pip install setuptools wheel pyinstaller && \
          pip install -r requirements.txt
      - name: create background-extraction-linux bundle
        run: pyinstaller --onefile -n background-extraction-linux ./src/gui.py
      - name: store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: background-extraction-linux
          path: ./dist/background-extraction-linux
          retention-days: 1

  build-windows:
    runs-on: windows-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          pip install setuptools wheel pyinstaller && `
          pip install -r requirements.txt
# pip install -r requirements-c11.3-win.txt -f https://download.pytorch.org/whl/cu113/torch_stable.html && `
      - name: create background-extraction-win64 bundle
        run: pyinstaller.exe ./releng/win64.spec
      - name: store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: background-extraction-win64.exe
          path: ./dist/background-extraction-win64.exe
          retention-days: 1

  release:
    runs-one: ubuntu-latest
    needs: [build-linux, build-windows]
    steps:
      - name: download linux artifacts
        with:
          name: background-extraction-linux
      - name: download windows artifacts
        with:
          name: background-extraction-win64.exe
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            background-extraction-linux
            background-extraction-win64.exe
