# This is a basic workflow to help you get started with Actions

name: PyInstaller-Windows

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          pip install setuptools wheel pyinstaller && `
          pip install -r requirements-c11.3-win.txt -f https://download.pytorch.org/whl/cu113/torch_stable.html && `
          pip install -r requirements.txt
      - name: bundle be-c11.3-win
        run: pyinstaller.exe --clean -F ./releng/cuda-11.3-win.spec
      - name: store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bg-c11.3-win
          path: ./build/cuda-11.3-win/background-extraction-win-c11.3.exe
      #- name: Release
      #  uses: softprops/action-gh-release@v1
